<?php


namespace App\AdminModule\Presenters;

use Nette;


abstract class BasePresenter extends Nette\Application\UI\Presenter
{
    public $signaled = false;

    protected function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub
        if ($this->getSignal() !== false)
            $this->signaled = true;
    }

    protected function afterRender()
    {
        parent::afterRender(); // TODO: Change the autogenerated stub
        if ($this->isAjax()) {
            $this->redrawControl('content');
        }
    }


    public function beforeRender()
    {
        if (!$this->getUser()->isLoggedIn() || $this->getUser()->getRoles()[0] != 1) {
            $this->flashMessage('Nemáš sem přístup!');
            $this->redirect(':Homepage:default');
        }
    }

}